Fix deposit button alignment.
sul-dlss/happy-heron pull request #1541
Opened 2021-05-27 19:53 UTC by justinlittman

closes #1476

## Why was this change made?
Fix alignment when collection name is long.

## How was this change tested?
Locally

## Which documentation and/or configurations were updated?
NA

2021-05-27 19:53 UTC, justinlittman commented
Before:
![image](https://user-images.githubusercontent.com/588335/119888701-b48eda00-bf03-11eb-8797-e096d2e8f539.png)

2021-05-27 19:54 UTC, justinlittman commented
After:
![image](https://user-images.githubusercontent.com/588335/119888795-cec8b800-bf03-11eb-95e0-f51f73ab1f92.png)

2021-05-27 20:28 UTC, jcoyne requested changes
<img width="1159" alt="Screen Shot 2021-05-27 at 3 27 22 PM" src="https://user-images.githubusercontent.com/92044/119892669-0d5c7380-bf00-11eb-8cda-28f0e11baad7.png">
I'm seeing this layout on shorter titles.  Is that what is intended @astridu ?

2021-06-03 15:09 UTC, justinlittman commented
@astridu Is this acceptable?

2021-06-03 20:32 UTC, astridu commented
It's ok, but it would be nicer if the button was aligned with the title if you have the time. 
![image](https://user-images.githubusercontent.com/42216982/120708222-2b7e2280-c470-11eb-988b-99732f7821b4.png)

2021-06-04 00:24 UTC, jcoyne approved these changes

2021-06-04 11:54 UTC, justinlittman commented
Skill is the limiting factor @astridu.

2021-06-04 11:54 UTC, merged