[HOLD] Fix state filter in item admin report.
sul-dlss/happy-heron pull request #2515
Opened 2022-08-26 16:26 UTC by justinlittman

closes #2513

## Why was this change made? 🤔
Users were getting incorrect report results.

## How was this change tested? 🤨

⚡ ⚠ If this change involves consuming from or writing to another service (or shared file system), ***run [integration test create_object_h2_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test manually in [stage|qa] environment, in addition to specs. ⚡

QA, Amy

2022-08-26 16:32 UTC, jcoyne commented on app/views/admin/work_reports/new.html.erb
> +          <%= form.collection_check_boxes(:state, states_in_order.map { |state| [state.to_s, I18n.t(state, scope: 'work.state')] }, :first, :last, include_hidden: false) do |b| %>
If you make this change, then https://github.com/sul-dlss/happy-heron/blob/main/app/services/admin/work_report_query.rb#L35 should also be changed. that line was stripping out the empty one.

2022-08-26 20:45 UTC, justinlittman commented
@amyehodge approved

2022-08-29 12:55 UTC, jcoyne approved these changes

2022-08-29 12:56 UTC, jcoyne requested changes
Can you add a test that shows how this fixed the situation?

2022-08-29 16:05 UTC, justinlittman commented
@jcoyne I'm a bit flumoxed on how to test this. My first inclination was to add it to the `work_report_spec` feature test. However, while I can test the headers, I can't seem to access the correct response body. (Based on googling, this seems driver-specific.)

I don't think that a request spec would add any value because the fix is in what is being sent from the browser.

Open to other suggestions.

2022-08-29 16:21 UTC, jcoyne commented
@justinlittman I can't see how this is different functionally from what was there before. 🤷

2022-08-29 17:09 UTC, justinlittman commented
It fixes two problems:
* While hidden empty state was being handled in the query service, it was causing problems in other: https://github.com/sul-dlss/happy-heron/issues/2513#issuecomment-1228675864
* The multiple state fields were being treated as a string, not an array, by param parsing.

2022-08-29 17:25 UTC, justinlittman commented
Replaced by #2530

2022-08-29 17:25 UTC, closed without merging