ensure all popovers have aria-describedBy
sul-dlss/happy-heron pull request #3186
Opened 2023-07-05 20:32 UTC by peetucket

# Why was this change made? 🤔

Fixes accessibility items in #3171 

# How was this change tested? 🤨

Localhost

2023-07-06 13:13 UTC, justinlittman requested changes
Also, can you add comments to PopoverComponent describing the accessibility-correct way to use it.

2023-07-06 16:48 UTC, peetucket commented on app/components/first_draft_collections/create/details_component.html.erb
> +      <%= form.label :name, "Collection name *", class: "col-form-label", "aria-describedby": "popover-collection.name" %>
good question - i was assuming the description was of the input, but i could be convinced it was the label too... we can verify with an expert

2023-07-06 16:50 UTC, peetucket commented on app/components/collections/edit_license_component.html.erb
> +  <section id="terms" data-controller="complex-radio" aria-describedby="popover-collection.terms">
oops...this change adding the corresponding`id` is on the `PopoverComponent` and incorrectly got pulled into a different already merged PR.  The ID is now added to any element via the `PopoverComponent` in main: https://github.com/sul-dlss/happy-heron/blob/main/app/components/popover_component.html.erb#L1

The ID is based on the key, which is the change I added here.

2023-07-06 21:30 UTC, peetucket commented on app/components/first_draft_collections/create/details_component.html.erb
> +      <%= form.label :name, "Collection name *", class: "col-form-label", "aria-describedby": "popover-collection.name" %>
I think this is correct ... it is and should be the label, this is what is the tooltip is right next to and is what it is tied to

2023-07-06 21:39 UTC, peetucket commented on app/components/collections/edit_license_component.html.erb
> +  <section id="terms" data-controller="complex-radio" aria-describedby="popover-collection.terms">
I rebased from main to ensure the needed change from `PopoverComponent` is visible in this PR.

2023-07-06 21:40 UTC, peetucket commented
> Also, can you add comments to PopoverComponent describing the accessibility-correct way to use it.

I added a comment to the top of `PopoverComponent` explaining how to use it.

2023-07-07 11:27 UTC, justinlittman commented on app/components/first_draft_collections/create/details_component.html.erb
> +      <%= form.label :name, "Collection name *", class: "col-form-label", "aria-describedby": "popover-collection.name" %>
Right, but the label is tied to the input. So if the label is describing the input then isn't the tooltip also describing the input?

2023-07-07 11:29 UTC, justinlittman approved these changes
Approve and defer to you on determining whether popover should reference the label or input.

2023-07-17 22:01 UTC, peetucket commented
Note, after looking at https://inclusive-components.design/tooltips-toggletips/#inclusivetoggletips will leave this as is with aria-describedby tags, but have now moved the element they are attached to in some cases.  Where it made sense, I moved to the form input being described. In some cases the tip is describing a section, so left on the label or legend in those cases.

2023-07-17 22:10 UTC, merged