sorbet rbi autogen
sul-dlss/happy-heron pull request #511
Opened 2020-11-19 06:25 UTC by jmartin-sul

## Why was this change made?

`bundle exec srb rbi gems && bundle exec rake rails_rbi:all && bundle exec srb rbi hidden-definitions && bundle exec srb rbi suggest-typed`

because why not.

i'd originally tacked this onto #456, but then i split it out into its own PR -- if it'd make for a painful rebase or something, feel free to close.  didn't take long, not super necessary.

## How was this change tested?

unit tests

## Which documentation and/or configurations were updated?

n/a

2020-11-19 15:50 UTC, jcoyne requested changes

2020-11-19 15:50 UTC, jcoyne commented on sorbet/rbi/gems/actionpack.rbi
> +module ActionController::ApiRendering
Doing this just causes a bunch of churn (in `sorbet/rbi/gems`).  The RBI files do not generate in a cannonical way, so we get changes in the repo with no meaningful impact.

2020-12-01 22:26 UTC, ndushay commented
I'm closing this PR.  I know sorbet updates have happened since this PR in any case.

2020-12-01 22:26 UTC, closed without merging

2020-12-01 23:17 UTC, jmartin-sul commented
> I'm closing this PR. I know sorbet updates have happened since this PR in any case.

ah yeah, thanks, meant to do that myself