Remove email domain from display of email usernames
sul-dlss/happy-heron pull request #721
Opened 2020-12-08 22:36 UTC by aaron-collier

## Why was this change made?

Fixes #692 

Before:

<img width="1496" alt="Screen Shot 2020-12-08 at 2 35 12 PM" src="https://user-images.githubusercontent.com/2294288/101549507-a8698d00-3962-11eb-96ce-1796db2c1ea8.png">

After:

<img width="1505" alt="Screen Shot 2020-12-08 at 2 35 28 PM" src="https://user-images.githubusercontent.com/2294288/101549514-ac95aa80-3962-11eb-8dd0-6b77b48bf21f.png">

## How was this change tested?

Updated unit and request tests

## Which documentation and/or configurations were updated?

2020-12-08 23:01 UTC, jcoyne requested changes
Can we use `collection.creator.sunetid` throughout?

2020-12-08 23:06 UTC, aaron-collier commented
@jcoyne yeah, I just saw that when working on another PR. Will do. I wasn't entirely sure if they would always be sunets, but I suspect that only makes sense.

2020-12-08 23:29 UTC, aaron-collier commented
@jcoyne done.

2020-12-09 00:14 UTC, mjgiarlo approved these changes

2020-12-09 00:30 UTC, jcoyne approved these changes

2020-12-09 00:30 UTC, merged